import { TRAINING_DEFAULTS } from '@/config/training-defaults';

import type { Difficulty, Equipment, ForceDirection, Mechanic, MuscleGroup } from './schema';

/**
 * Seed library (PRD B1). 60 exercises covering every major movement pattern:
 * squat, hinge, lunge, horizontal/vertical push, horizontal/vertical pull,
 * shoulder/arm/leg accessories, core, carries, and one power lift.
 *
 * Instruction text is a placeholder (PRD B3 allows this at MVP); rest
 * defaults come from config unless an entry overrides.
 */
export interface SeedExercise {
  name: string;
  aliases: string[];
  primaryMuscle: MuscleGroup;
  secondaryMuscles: MuscleGroup[];
  equipment: Equipment;
  mechanic: Mechanic;
  force: ForceDirection;
  difficulty: Difficulty;
  /** Overrides the mechanic-based default when provided. */
  defaultRestSeconds?: number;
}

export const SEED_INSTRUCTION_PLACEHOLDER =
  'Coaching instructions arrive with the exercise library content pass.';

export function seedRestSeconds(exercise: SeedExercise): number {
  return exercise.defaultRestSeconds ?? TRAINING_DEFAULTS.restSeconds[exercise.mechanic];
}

export const SEED_EXERCISES: SeedExercise[] = [
  // --- Squat pattern ---
  {
    name: 'Back Squat',
    aliases: ['Squat'],
    primaryMuscle: 'quads',
    secondaryMuscles: ['hamstrings', 'glutes', 'core'],
    equipment: 'barbell',
    mechanic: 'compound',
    force: 'push',
    difficulty: 'intermediate',
  },
  {
    name: 'Front Squat',
    aliases: [],
    primaryMuscle: 'quads',
    secondaryMuscles: ['core', 'glutes', 'upper-back'],
    equipment: 'barbell',
    mechanic: 'compound',
    force: 'push',
    difficulty: 'intermediate',
  },
  {
    name: 'Goblet Squat',
    aliases: [],
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'core'],
    equipment: 'kettlebell',
    mechanic: 'compound',
    force: 'push',
    difficulty: 'beginner',
  },
  {
    name: 'Leg Press',
    aliases: [],
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes'],
    equipment: 'machine',
    mechanic: 'compound',
    force: 'push',
    difficulty: 'beginner',
  },
  {
    name: 'Bulgarian Split Squat',
    aliases: [],
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'core'],
    equipment: 'dumbbell',
    mechanic: 'compound',
    force: 'push',
    difficulty: 'intermediate',
  },
  {
    name: 'Hack Squat',
    aliases: [],
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes'],
    equipment: 'machine',
    mechanic: 'compound',
    force: 'push',
    difficulty: 'intermediate',
  },

  // --- Hinge pattern ---
  {
    name: 'Deadlift',
    aliases: ['Conventional Deadlift'],
    primaryMuscle: 'hamstrings',
    secondaryMuscles: ['glutes', 'lower-back', 'traps', 'forearms'],
    equipment: 'barbell',
    mechanic: 'compound',
    force: 'pull',
    difficulty: 'advanced',
  },
  {
    name: 'Sumo Deadlift',
    aliases: [],
    primaryMuscle: 'hamstrings',
    secondaryMuscles: ['glutes', 'quads', 'lower-back'],
    equipment: 'barbell',
    mechanic: 'compound',
    force: 'pull',
    difficulty: 'advanced',
  },
  {
    name: 'Trap Bar Deadlift',
    aliases: ['Hex Bar Deadlift'],
    primaryMuscle: 'quads',
    secondaryMuscles: ['hamstrings', 'glutes', 'traps'],
    equipment: 'other',
    mechanic: 'compound',
    force: 'pull',
    difficulty: 'intermediate',
  },
  {
    name: 'Romanian Deadlift',
    aliases: ['RDL'],
    primaryMuscle: 'hamstrings',
    secondaryMuscles: ['glutes', 'lower-back'],
    equipment: 'barbell',
    mechanic: 'compound',
    force: 'pull',
    difficulty: 'intermediate',
  },
  {
    name: 'Single-Leg Romanian Deadlift',
    aliases: ['Single-Leg RDL'],
    primaryMuscle: 'hamstrings',
    secondaryMuscles: ['glutes', 'core'],
    equipment: 'dumbbell',
    mechanic: 'compound',
    force: 'pull',
    difficulty: 'intermediate',
  },
  {
    name: 'Hip Thrust',
    aliases: [],
    primaryMuscle: 'glutes',
    secondaryMuscles: ['hamstrings', 'core'],
    equipment: 'barbell',
    mechanic: 'compound',
    force: 'push',
    difficulty: 'beginner',
  },
  {
    name: 'Back Extension',
    aliases: ['Hyperextension'],
    primaryMuscle: 'hamstrings',
    secondaryMuscles: ['glutes', 'lower-back'],
    equipment: 'bodyweight',
    mechanic: 'isolation',
    force: 'pull',
    difficulty: 'beginner',
  },

  // --- Lunge / single-leg ---
  {
    name: 'Walking Lunge',
    aliases: [],
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: 'dumbbell',
    mechanic: 'compound',
    force: 'push',
    difficulty: 'beginner',
  },
  {
    name: 'Reverse Lunge',
    aliases: [],
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes', 'core'],
    equipment: 'dumbbell',
    mechanic: 'compound',
    force: 'push',
    difficulty: 'beginner',
  },
  {
    name: 'Step-Up',
    aliases: [],
    primaryMuscle: 'quads',
    secondaryMuscles: ['glutes'],
    equipment: 'dumbbell',
    mechanic: 'compound',
    force: 'push',
    difficulty: 'beginner',
  },

  // --- Horizontal push ---
  {
    name: 'Barbell Bench Press',
    aliases: ['Bench Press'],
    primaryMuscle: 'chest',
    secondaryMuscles: ['front-delts', 'triceps'],
    equipment: 'barbell',
    mechanic: 'compound',
    force: 'push',
    difficulty: 'intermediate',
  },
  {
    name: 'Incline Barbell Bench Press',
    aliases: ['Incline Bench Press'],
    primaryMuscle: 'chest',
    secondaryMuscles: ['front-delts', 'triceps'],
    equipment: 'barbell',
    mechanic: 'compound',
    force: 'push',
    difficulty: 'intermediate',
  },
  {
    name: 'Dumbbell Bench Press',
    aliases: [],
    primaryMuscle: 'chest',
    secondaryMuscles: ['front-delts', 'triceps'],
    equipment: 'dumbbell',
    mechanic: 'compound',
    force: 'push',
    difficulty: 'beginner',
  },
  {
    name: 'Machine Chest Press',
    aliases: [],
    primaryMuscle: 'chest',
    secondaryMuscles: ['front-delts', 'triceps'],
    equipment: 'machine',
    mechanic: 'compound',
    force: 'push',
    difficulty: 'beginner',
  },
  {
    name: 'Push-Up',
    aliases: ['Press-Up'],
    primaryMuscle: 'chest',
    secondaryMuscles: ['front-delts', 'triceps', 'core'],
    equipment: 'bodyweight',
    mechanic: 'compound',
    force: 'push',
    difficulty: 'beginner',
  },
  {
    name: 'Chest Dip',
    aliases: [],
    primaryMuscle: 'chest',
    secondaryMuscles: ['front-delts', 'triceps'],
    equipment: 'bodyweight',
    mechanic: 'compound',
    force: 'push',
    difficulty: 'intermediate',
  },

  // --- Vertical push ---
  {
    name: 'Barbell Overhead Press',
    aliases: ['OHP', 'Overhead Press', 'Military Press'],
    primaryMuscle: 'front-delts',
    secondaryMuscles: ['side-delts', 'triceps', 'core'],
    equipment: 'barbell',
    mechanic: 'compound',
    force: 'push',
    difficulty: 'intermediate',
  },
  {
    name: 'Push Press',
    aliases: [],
    primaryMuscle: 'front-delts',
    secondaryMuscles: ['side-delts', 'triceps', 'quads'],
    equipment: 'barbell',
    mechanic: 'compound',
    force: 'push',
    difficulty: 'intermediate',
  },
  {
    name: 'Seated Dumbbell Shoulder Press',
    aliases: [],
    primaryMuscle: 'front-delts',
    secondaryMuscles: ['side-delts', 'triceps'],
    equipment: 'dumbbell',
    mechanic: 'compound',
    force: 'push',
    difficulty: 'beginner',
  },
  {
    name: 'Arnold Press',
    aliases: [],
    primaryMuscle: 'front-delts',
    secondaryMuscles: ['side-delts', 'triceps'],
    equipment: 'dumbbell',
    mechanic: 'compound',
    force: 'push',
    difficulty: 'intermediate',
  },

  // --- Horizontal pull ---
  {
    name: 'Barbell Row',
    aliases: ['Bent-Over Row'],
    primaryMuscle: 'upper-back',
    secondaryMuscles: ['lats', 'biceps', 'lower-back'],
    equipment: 'barbell',
    mechanic: 'compound',
    force: 'pull',
    difficulty: 'intermediate',
  },
  {
    name: 'One-Arm Dumbbell Row',
    aliases: ['Single-Arm Row'],
    primaryMuscle: 'lats',
    secondaryMuscles: ['upper-back', 'biceps'],
    equipment: 'dumbbell',
    mechanic: 'compound',
    force: 'pull',
    difficulty: 'beginner',
  },
  {
    name: 'Seated Cable Row',
    aliases: [],
    primaryMuscle: 'upper-back',
    secondaryMuscles: ['lats', 'biceps'],
    equipment: 'cable',
    mechanic: 'compound',
    force: 'pull',
    difficulty: 'beginner',
  },
  {
    name: 'Inverted Row',
    aliases: ['Australian Pull-Up', 'Bodyweight Row'],
    primaryMuscle: 'upper-back',
    secondaryMuscles: ['lats', 'biceps', 'core'],
    equipment: 'bodyweight',
    mechanic: 'compound',
    force: 'pull',
    difficulty: 'beginner',
  },

  // --- Vertical pull ---
  {
    name: 'Pull-Up',
    aliases: [],
    primaryMuscle: 'lats',
    secondaryMuscles: ['upper-back', 'biceps', 'core'],
    equipment: 'bodyweight',
    mechanic: 'compound',
    force: 'pull',
    difficulty: 'intermediate',
  },
  {
    name: 'Chin-Up',
    aliases: [],
    primaryMuscle: 'lats',
    secondaryMuscles: ['biceps', 'upper-back'],
    equipment: 'bodyweight',
    mechanic: 'compound',
    force: 'pull',
    difficulty: 'intermediate',
  },
  {
    name: 'Lat Pulldown',
    aliases: [],
    primaryMuscle: 'lats',
    secondaryMuscles: ['upper-back', 'biceps'],
    equipment: 'cable',
    mechanic: 'compound',
    force: 'pull',
    difficulty: 'beginner',
  },
  {
    name: 'Straight-Arm Pulldown',
    aliases: [],
    primaryMuscle: 'lats',
    secondaryMuscles: ['core'],
    equipment: 'cable',
    mechanic: 'isolation',
    force: 'pull',
    difficulty: 'beginner',
  },

  // --- Shoulder accessory ---
  {
    name: 'Dumbbell Lateral Raise',
    aliases: [],
    primaryMuscle: 'side-delts',
    secondaryMuscles: ['traps'],
    equipment: 'dumbbell',
    mechanic: 'isolation',
    force: 'push',
    difficulty: 'beginner',
  },
  {
    name: 'Face Pull',
    aliases: [],
    primaryMuscle: 'rear-delts',
    secondaryMuscles: ['upper-back', 'traps'],
    equipment: 'cable',
    mechanic: 'isolation',
    force: 'pull',
    difficulty: 'beginner',
  },
  {
    name: 'Reverse Pec-Deck',
    aliases: ['Rear Delt Fly'],
    primaryMuscle: 'rear-delts',
    secondaryMuscles: ['upper-back'],
    equipment: 'machine',
    mechanic: 'isolation',
    force: 'pull',
    difficulty: 'beginner',
  },
  {
    name: 'Barbell Shrug',
    aliases: [],
    primaryMuscle: 'traps',
    secondaryMuscles: ['forearms'],
    equipment: 'barbell',
    mechanic: 'isolation',
    force: 'pull',
    difficulty: 'beginner',
  },

  // --- Biceps ---
  {
    name: 'Barbell Curl',
    aliases: [],
    primaryMuscle: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: 'barbell',
    mechanic: 'isolation',
    force: 'pull',
    difficulty: 'beginner',
  },
  {
    name: 'Dumbbell Hammer Curl',
    aliases: ['Hammer Curl'],
    primaryMuscle: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: 'dumbbell',
    mechanic: 'isolation',
    force: 'pull',
    difficulty: 'beginner',
  },
  {
    name: 'Incline Dumbbell Curl',
    aliases: [],
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: 'dumbbell',
    mechanic: 'isolation',
    force: 'pull',
    difficulty: 'intermediate',
  },
  {
    name: 'Preacher Curl',
    aliases: [],
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: 'machine',
    mechanic: 'isolation',
    force: 'pull',
    difficulty: 'beginner',
  },

  // --- Triceps ---
  {
    name: 'Close-Grip Bench Press',
    aliases: [],
    primaryMuscle: 'triceps',
    secondaryMuscles: ['chest', 'front-delts'],
    equipment: 'barbell',
    mechanic: 'compound',
    force: 'push',
    difficulty: 'intermediate',
  },
  {
    name: 'Lying Triceps Extension',
    aliases: ['Skull Crusher', 'Skullcrusher'],
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: 'barbell',
    mechanic: 'isolation',
    force: 'push',
    difficulty: 'intermediate',
  },
  {
    name: 'Cable Triceps Pushdown',
    aliases: ['Pushdown', 'Triceps Pushdown'],
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: 'cable',
    mechanic: 'isolation',
    force: 'push',
    difficulty: 'beginner',
  },
  {
    name: 'Overhead Cable Triceps Extension',
    aliases: [],
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: 'cable',
    mechanic: 'isolation',
    force: 'push',
    difficulty: 'beginner',
  },
  {
    name: 'Bench Dip',
    aliases: [],
    primaryMuscle: 'triceps',
    secondaryMuscles: ['front-delts'],
    equipment: 'bodyweight',
    mechanic: 'isolation',
    force: 'push',
    difficulty: 'beginner',
  },

  // --- Leg accessory ---
  {
    name: 'Leg Extension',
    aliases: [],
    primaryMuscle: 'quads',
    secondaryMuscles: [],
    equipment: 'machine',
    mechanic: 'isolation',
    force: 'push',
    difficulty: 'beginner',
  },
  {
    name: 'Lying Leg Curl',
    aliases: [],
    primaryMuscle: 'hamstrings',
    secondaryMuscles: ['calves'],
    equipment: 'machine',
    mechanic: 'isolation',
    force: 'pull',
    difficulty: 'beginner',
  },
  {
    name: 'Standing Calf Raise',
    aliases: [],
    primaryMuscle: 'calves',
    secondaryMuscles: [],
    equipment: 'machine',
    mechanic: 'isolation',
    force: 'push',
    difficulty: 'beginner',
  },
  {
    name: 'Seated Calf Raise',
    aliases: [],
    primaryMuscle: 'calves',
    secondaryMuscles: [],
    equipment: 'machine',
    mechanic: 'isolation',
    force: 'push',
    difficulty: 'beginner',
  },

  // --- Glutes ---
  {
    name: 'Hip Abduction',
    aliases: [],
    primaryMuscle: 'glutes',
    secondaryMuscles: [],
    equipment: 'machine',
    mechanic: 'isolation',
    force: 'push',
    difficulty: 'beginner',
  },

  // --- Core ---
  {
    name: 'Plank',
    aliases: [],
    primaryMuscle: 'core',
    secondaryMuscles: ['obliques'],
    equipment: 'bodyweight',
    mechanic: 'isolation',
    force: 'static',
    difficulty: 'beginner',
  },
  {
    name: 'Hanging Leg Raise',
    aliases: [],
    primaryMuscle: 'core',
    secondaryMuscles: ['obliques', 'forearms'],
    equipment: 'bodyweight',
    mechanic: 'isolation',
    force: 'pull',
    difficulty: 'intermediate',
  },
  {
    name: 'Ab Wheel Rollout',
    aliases: ['Ab Rollout'],
    primaryMuscle: 'core',
    secondaryMuscles: ['obliques', 'lats'],
    equipment: 'other',
    mechanic: 'compound',
    force: 'push',
    difficulty: 'intermediate',
  },
  {
    name: 'Cable Crunch',
    aliases: [],
    primaryMuscle: 'core',
    secondaryMuscles: [],
    equipment: 'cable',
    mechanic: 'isolation',
    force: 'pull',
    difficulty: 'beginner',
  },
  {
    name: 'Dead Bug',
    aliases: [],
    primaryMuscle: 'core',
    secondaryMuscles: ['obliques'],
    equipment: 'bodyweight',
    mechanic: 'isolation',
    force: 'static',
    difficulty: 'beginner',
  },

  // --- Carries ---
  {
    name: "Farmer's Carry",
    aliases: ["Farmer's Walk", 'Farmers Walk'],
    primaryMuscle: 'core',
    secondaryMuscles: ['forearms', 'traps', 'obliques'],
    equipment: 'dumbbell',
    mechanic: 'compound',
    force: 'static',
    difficulty: 'beginner',
  },
  {
    name: 'Suitcase Carry',
    aliases: [],
    primaryMuscle: 'obliques',
    secondaryMuscles: ['core', 'forearms'],
    equipment: 'dumbbell',
    mechanic: 'compound',
    force: 'static',
    difficulty: 'beginner',
  },

  // --- Power ---
  {
    name: 'Power Clean',
    aliases: ['Clean'],
    primaryMuscle: 'quads',
    secondaryMuscles: ['traps', 'lats', 'hamstrings', 'core'],
    equipment: 'barbell',
    mechanic: 'compound',
    force: 'pull',
    difficulty: 'advanced',
  },
];
